#! /bin/sh
python3 multiSpider.py 游标卡尺 youbiaokachi
python3 multiSpider.py 运动鞋 yundongxie
python3 multiSpider.py 庭院盆摘 tingyuanpenzhai
python3 multiSpider.py 钢笔圆珠笔 gangbiyuanzhubi
python3 multiSpider.py 口红 kouhong
python3 multiSpider.py 自拍杆 zipaigan
python3 multiSpider.py 玻璃瓶 boliping
python3 multiSpider.py 女士背包 nvshibeibao
python3 multiSpider.py 手表 shoubiao
python3 multiSpider.py 房屋平面图 fangwupingmiantu
python3 multiSpider.py 饭店聚餐 fandianjucan
python3 multiSpider.py 高速护栏 gaosuhulan
python3 multiSpider.py 拖拉机 tuolaji
python3 multiSpider.py 铲子 chanzi
python3 multiSpider.py 亭台楼阁 tingtailouge
python3 multiSpider.py 木签烧烤 muqianshaokao
python3 multiSpider.py 栈道 zhandao
python3 multiSpider.py 汽车内饰 qicheneishi
python3 multiSpider.py 三角架 sanjiaojia
python3 multiSpider.py 挂衣架 guayijia
python3 multiSpider.py 芒果水果 mangguoshuiguo
python3 multiSpider.py 香肠 xiangchang
python3 multiSpider.py 流程表报表 liuchengbiaobaobiao
python3 multiSpider.py 帐篷 zhangpeng
python3 multiSpider.py 桌椅衣柜 zhuoyiyigui
python3 multiSpider.py 橱柜餐具 chuguicanju
python3 multiSpider.py 超市货架 chaoshihuojia
python3 multiSpider.py 天猫零食 tianmaolingshi
python3 multiSpider.py 电塔 dianta
python3 multiSpider.py 螺纹螺管 luowenluoguan
python3 multiSpider.py 轮船 lunchuan
python3 multiSpider.py 机械臂 jixiebi
python3 multiSpider.py 水龙头 shuilongtou
python3 multiSpider.py 自行车摩托车 zixingchemotuoche
python3 multiSpider.py 门面店招牌 menmiandianzhaopai
python3 multiSpider.py 酒水饮料 jiushuiyinliao
python3 multiSpider.py 电钻 dianzuan
python3 multiSpider.py 健身器械 jianshenqixie
python3 multiSpider.py 手机支架 shoujizhijia
python3 multiSpider.py 酒吧 jiuba
